### ISSUE TITLE
Missing example for walrus operator in Chapter1/variable.ipynb

### ISSUE THREAD

**Issue by Quakumei** [khuyentran1401/Efficient_Python_tricks_and_tools_for_data_scientists#11]
![image](https://user-images.githubusercontent.com/53406289/215327523-ef39afc9-86de-47f5-8647-7d1069146051.png)

Missing refactored example of code with making use of walrus operator.

**Comment by khuyentran1401** [comment]
Thank you for the issue. I fixed it under the [good practices section](https://khuyentran1401.github.io/Efficient_Python_tricks_and_tools_for_data_scientists/Chapter1/good_practices.html#walrus-operator-assign-a-variable-in-an-expression).
